repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.*.yml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
        exclude: tests/
      - id: trailing-whitespace
        exclude: tests/|.*juvix
      - id: end-of-file-fixer
        exclude: tests/|assets/

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        name: forbid binary files
        exclude: docs/assets/|docs/overrides/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or: [css, javascript, yaml, toml]
        exclude: .*/juvix-packages.md|.*/juvix.lock.yaml

  - repo: local
    hooks:
      - id: check-format-juvix-files
        name: check format Juvix files
        entry: make check-format-juvix-files
        language: system
        verbose: true
        pass_filenames: false

      - id: typecheck-juvix-files
        name: typecheck Juvix files
        entry: make typecheck-juvix-files
        language: system
        verbose: true
        pass_filenames: false
