authors:
  jonathan:
    name: Jonathan Cubides
    description: Heliax
    avatar: https://github.com/jonaprieto.png

  jan:
    name: Jan Mas Rovira
    description: Heliax
    avatar: https://github.com/janmasrovira.png

  paul:
    name: Paul Cadman
    description: Heliax
    avatar: https://github.com/paulcadman.png

  lukasz:
    name: Łukasz Czajka
    description: Heliax
    avatar: https://github.com/lukaszcz.png

  artem:
    name: Artem Gureev
    description: Heliax
    avatar: https://github.com/vrom911.png

  veronika:
    name: Veronika Romashkina
    description: Heliax
    avatar: https://github.com/vrom911.png
